spring:
  # Data source configuration
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/hunters_league_db
  #   username: admin
  #   password: admin
  #   driver-class-name: org.postgresql.Driver

  # Docker compose configuration
  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only

  # Liquibase configuration
  liquibase:
    change-log: db/changelog/master.yaml

  # Exclude auto-configuration for security
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  # Mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_USERNAME}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Optional external configuration file import
  config:
    import: optional:file:.env[.properties]

# JWT security configuration
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000
